### ISSUE TITLE
How i can debug what happened?

### ISSUE THREAD

**Issue by byniow** [pawelka/sofarsolar_esp_rs485_logger#10]
I make this project. Used ESP07 with different plate. I connect TXD, RXD, power supply. In project You show connectRS485 converter to 5V directly. Why? Logic work at 5V too, but ESP cannot. I damaged one ESP by this. Ok, i program new one, RXD led on module blink by 20-40ms every 5s (i set this interval) but nothing else not happened. TX LED not blinks, telnet show every 5s something like "took loop 2110", homeassistant not receive any mqtt data. In MQTT broker i see connected module, but no any data. 
Please tell me about prepare inverter to work, how look correct log from telnet, how read raw data between ESP and HomeAssistant, how set correct topic, detailed pinout ESP<>RS485, Any way to debug why not work.....

**Comment by pawelka** [comment]
Try to use ESPHome approach, there is seamless integration with HA. Additionally for full debug you can change logger level to VERY_VERBOSE
