### ISSUE TITLE
SofarSolar MQTT Domoticz

### ISSUE THREAD

**Issue by ozogp** [pawelka/sofarsolar_esp_rs485_logger#11]
Dobry wieczór, mam dwa pytania:
Czy może jest rozważany projekt identycznego loggera ale obsługującego Domoticza? 
Jaki dokładnie rejestr odpowiada za  "energy_today" ?

**Comment by ilexpl01** [comment]
Zainstaluj sobie Node-Red i przerabiaj komunikaty MQTT. Mnie to działa.

**Comment by pawelka** [comment]
Dla Domoticza może użyć podejście z Tasmota, nie powinno być problemu z integracją. Nie znam Domoticza ale wiem, że Tasmota z nim się integruje.

**Comment by Kosa1978** [comment]
Jak wgrać/skompilować plik z ustawieniami tasmota? wgrałem już tasmote na wemosa i teraz jak wgrać plik o rozszerzeniu .....h ?
