### ISSUE TITLE
no access point

### ISSUE THREAD

**Issue by tempod** [pawelka/sofarsolar_esp_rs485_logger#13]
Hello to all.
I was able to successfully flash esp-07.bin file on ESP07 with NodeMCU Flasher.
After the flash I unplug the card, move the selector from "program" to "uart", and restart it. But I can't find any access points to connect to.
What did I do wrong?
Thanks.
![esp07](https://user-images.githubusercontent.com/71033514/135757992-748f526d-d390-4d0f-ac4e-42e43ed927af.jpg)

**Comment by tempod** [comment]
ok. i bought a new esp8266 module, an esp12f, and now it works.
But I think there is an error in the configuration. In the home assistant configuration I had to change all values from

`state_topic: "inverter/status"`

to

`state_topic: "inverter"`

and now works fine.

![Immagine 2021-10-07 005524](https://user-images.githubusercontent.com/71033514/136294620-9c96f0e8-5640-4019-9b35-246ab52cd388.jpg)

**Comment by pawelka** [comment]
Try to use ESPHome approach, there is seamless integration with HA.
