### ISSUE TITLE
energy meters 

### ISSUE THREAD

**Issue by Toma82** [pawelka/sofarsolar_esp_rs485_logger#17]
Did you test this solution for reading parameters from energy meters that have Modbus RTU, e.g. F&F LE-01MW?

**Comment by pawelka** [comment]
Not yet, but in theory it should work. I bough 1 phase energy meter and plan to test with it. You need to only change registers addresses to be compliant with energy meter spec.

**Comment by pawelka** [comment]
Obsolate
