### ISSUE TITLE
"inverter_energy_total" not recognizsed as Energy entity

### ISSUE THREAD

**Issue by jpier123** [pawelka/sofarsolar_esp_rs485_logger#18]
Obie wartości pomiaru energy [dzienny i total] nie dają się zastosować do pomiaru statystycznego oraz nie występują w panelu ENERGY.

Próbowałem dodać "sensor.sofarsolar_energy_today" lub "sensor.sofarsolar_energy_total" do panelu licznika energi, ale to entity nie zostaje wyświetlone podczas przeglądania listy. Posiadam także licznik ZAMEL MEW01 i pomiary energii [kWh] tego urzadzenia są wyświetlane. Myślę że problem jest nie z użytą [device_class: "power"] a brakiem [State class "total_increasing"].
 Proszę o komentarz.

Pozdrawiam i  dziękuję za udostępnienie integracji.

Jarek.

**Comment by jpier123** [comment]
Device class type change did the trick: 

 energy | Wh, kWh, MWh | Energy, statistics will be stored in kWh. [Source](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)


    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy

**Comment by pawelka** [comment]
Thank for hint, I'll update config.
