### ISSUE TITLE
Logger na nodemcu

### ISSUE THREAD

**Issue by mobopx** [pawelka/sofarsolar_esp_rs485_logger#19]
Hej Paweł, zrobiłem ten logger na nodemcu zamiast ESP07. Widzę wszystkie encje w HA, ale ze statusem "nieznany" (oprócz sekcji Diagnostyka, tam encje są ok). Czy jakieś zmiany w kodzie ESPHome trzeba zrobić, aby to zaskoczyło?

**Comment by pawelka** [comment]
na pewno "board" trzeba zmienić i zaktualizować oznaczenie pinów, może być inne.

**Comment by mobopx** [comment]
> na pewno "board" trzeba zmienić i zaktualizować oznaczenie pinów, może być inne.

Board jest ten sam co na ESP07 (sprawdzałem kontrolnie na innych nodemcu, których używam). Log w ESPHome jest bez błędów. Numery pinów RX i TX ustrawiłem pod nodemcu i pomysły mi się skończyły :/

**Comment by mobopx** [comment]
a mógłbyś udostępnić kod ESPHome z prototypu na D1 mini (jeśli jeszcze go masz)? 
Spróbuję przez Wemosa się połączyć. 
Dzięki

**Comment by amilotxak24** [comment]
mobopx rozwiązałeś problem ? Dziś zrobiłem instalke na d1 mini. Również nie mam odczytu żadnego wskazania z inwertera.

**Comment by pawelka** [comment]
A czy inwerter macie ustawione id na jeden. ModBus pozwala podłączyć wiele inwerterów na tej samej szynie i każdy inwerter musi mieć inne id, wówczas master ESP odpytuje o konkretny inwerter a inwerter do którego to jest przeznaczone odpowiada. Jak dobrze pamiętam na wyswietlaczu powinien pojawić się RS485 i numerek. W ustawieniach inwertera też można zmienić numerek. Dioda TX na konwerterze jak zamiga to na inwerterze pojawia się ikonka, a potem po TX, RX powinien zamigać na konwerterze, że inwerter coś odesłał.

**Comment by pawelka** [comment]
Nodemcu powinien mieć inny board bo ma pewnie inne pinout w stosunku do ESP07. Board powinien być nodemcuv2 
 https://esphome.io/devices/nodemcu_esp8266.html

**Comment by pawelka** [comment]
Co do D1 mini to spróbuj board:

  **board: d1_mini**

No i oczywiście potem tylko oznaczenia pinów aby się zgadzały z tym co jest skonfigurowane

**Comment by mobopx** [comment]
> mobopx rozwiązałeś problem ? Dziś zrobiłem instalke na d1 mini. Również nie mam odczytu żadnego wskazania z inwertera.

U mnie śmiga. Podrzucam config, może dopasujesz pod siebie, bo nie wiem do końca jak to ma być na wemosie.

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
    
uart:
  id: mod_bus
  tx_pin: GPIO16
  rx_pin: GPIO5
  baud_rate: 9600
  stop_bits: 1

Tylko te sekcje modyfikowałem względem configu od @pawelka

**Comment by tomchovanec** [comment]
Great work Paweł! Nowdays are the sofarsolar systems imported heavily to CZ from PL, but electricans are not even able to configure it properly to CZ specific mode (asymetric output)!. Thank you so much for showing me the way how to make it using EPSHome... I have also created custom wallbox using ETEK controller <-> modbus <-> ESP32 <-> mqtt <-> HASS and this is exactly what I've been looking for to make it all work together. I really appreciate your work!

**Comment by xury77** [comment]
Można też zrobić sobie na Esp8266 most rs485-TCP. Ja tak sobie zrobiłem na Tasmota i cały odczyt realizuję przez NodeRed'a.
Dzięki temu dochodzi sterowanie mocą, zdalne załączanie i wyłączanie inwertera oraz odczyt parametrów startowych i safetyvolt.
Do pełni szczęścia brakuje jedynie zapis parametrów przez niestandardowy FC 19. (0x13)

**Comment by pawelka** [comment]
Outdated

**Comment by tadatin** [comment]
The same problem still exists, i think, that this is related or the same issue as https://github.com/pawelka/sofarsolar_esp_rs485_logger/issues/24
Anyone solved this problem?
