### ISSUE TITLE
Disable Hotspot when connected to home network

### ISSUE THREAD

**Issue by stravinci** [pawelka/sofarsolar_esp_rs485_logger#2]
Hi,
it is possible to disable hotspot when logger is connected to home network with MQTT server?

**Comment by pawelka** [comment]
Good idea ;-) I'll add it, but no rush ;-)

**Comment by pawelka** [comment]
I checked the code and it's looks like AP is not enabled after connecting. For sure original sofar logger doesn't have an option to disable it. Maybe you are writing about original logger. I have the same problem and cannot disable AP for original logger.

**Comment by pawelka** [comment]
Expired. Closing ...
