### ISSUE TITLE
KTL-X G3

### ISSUE THREAD

**Issue by vibraterton** [pawelka/sofarsolar_esp_rs485_logger#20]
Cześć, planujesz dopasować binarki pod wersje falowników G3? Aktualnie mimo odbioru danych i przesyłu na MQTT wartości są puste

`{
  "status": "off",
  "fault_message": "",
  "dc_voltage_1": 0,
  "dc_current_1": 0,
  "dc_voltage_2": 0,
  "dc_current_2": 0,
  "ac_power": 0,
  "ac_frequency": 0,
  "ac_voltage_1": 0,
  "ac_current_1": 0,
  "ac_voltage_2": 0,
  "ac_current_2": 0,
  "ac_voltage_3": 0,
  "ac_current_3": 0,
  "energy_total": 0,
  "running_time": 0,
  "energy_today": 0,
  "temperature_module": 0,
  "temperature_inverter": 0,
  "bus_voltage": 0,
  "vice_cpu_input_voltage_1": 0,
  "countdown_timer": 0,
  "pv1_insulation_resistance": 0,
  "pv2_insulation_resistance": 0,
  "isolation_impedance": 0,
  "country_code?": 0,
  "phase_a_distribution": 0,
  "phase_b_distribution": 0,
  "phase_c_distribution": 0
}`

**Comment by pawelka** [comment]
Nie planuję, bo aby to ogarnąć to najlepiej mieć dokumentację, a sofarsolar nie udostępnia, czasami coś się da znaleźć albo falownik i metodą reverse engineeringu odkrywać jak koduje inwerter.

**Comment by blackscreener** [comment]
Na pewno musiałbyś skompilować wsad z nowymi adresami rejestrów. Sofar w G3 zmienił adresy w Modbusie, Najłatwiej ogarnąć to przez ESPHome.

**Comment by Floppe** [comment]
Anyone found G3 documentation or got it working?

**Comment by pawelka** [comment]
Won't fix.
