### ISSUE TITLE
Which MQTT library did you use ?

### ISSUE THREAD

**Issue by craigcurtin-dev** [pawelka/sofarsolar_esp_rs485_logger#3]
Hey Mate, Love what you have done here - i have a Solis 4G 3 phase unit and wish to adapt your code to work with that - trying to work out which of the ESP8266 MQTT libraries you used ?

I think i have worked out the other deps OK - just this one has got me stumped at the moment

Craig

**Comment by pawelka** [comment]
I'm using this one: https://github.com/256dpi/arduino-mqtt

**Comment by pawelka** [comment]
Closing.
