### ISSUE TITLE
Build for WemosD1 mini.

### ISSUE THREAD

**Issue by McKenzi84** [pawelka/sofarsolar_esp_rs485_logger#5]
Dear Sir, 

I would like to utilize Wemos D1 mini for this project.  Will "esp-07.bin" work with this device ?
And how to connect  RX and TX (Converter -> Wemos)  ? Your prototype was connected: RX->D1 , TX->D2. 
Thanks.

**Comment by pawelka** [comment]
No it won't work. The different image is needed for WemosD1

**Comment by pawelka** [comment]
I added wemos d1 mini image, but I didn't have time to check it. 

RX->D1 , TX->D2.

Please check and let me know.

**Comment by McKenzi84** [comment]
Thanks. I will check and post the result.

**Comment by McKenzi84** [comment]
Firmware  has been uploaded, initial config. went ok but i cannot re-enter configuration again . Device is connected to my network with assigned IP address . I was using "admin" as user, "AP password" as password. 
 Now i do not have acces to my inverter so i do not know is it  working or not. Shall i receive some MQTT messages while logger is not connected to inverter?

**Comment by pawelka** [comment]
"AP password" is name of the field which you had to enter during first setup, it's not a password. There is no mqtt message on connecting to inverter. To check if rs485 works correctly you can look at converter there should be diod that's blinks regularly (interval is part of configuration) and if inverter is working you should see second led blinking just after first. First blinks is command to just inverter, second one is a response. You should also something about rs485 one the inverter display.

**Comment by kudifm** [comment]
what password for wemos in ap mode?

**Comment by pawelka** [comment]
check "sofarsolar2mqtt", I'll add to README

**Comment by pawelka** [comment]
Please reopen if something is missing.
