### ISSUE TITLE
Am I able to do it?

### ISSUE THREAD

**Issue by toolpusher13** [pawelka/sofarsolar_esp_rs485_logger#8]
Hi there,
I am writing in english - maybe will be helpfull to somebody else, but I am polish. I guess there is such thing as private messages on github? I am interested in your project as I have Sofar KTL-X inverter. Thing is I have never had contact with anything like this in terms of software. Hardware is not a problem I found all the parts needed.  I am engineer, handy man but never used any programming tools or language. The question is:  am I able to do this basing an YT or web tutorials or would be better to stick to Solarman. Please advise  here or on toolpusher13(malpka)gmail.com If you like to...
Cheers,
Piotr

**Comment by pawelka** [comment]
Try to use ESPHome approach, there is seamless integration with HA. You can also find planty of tutorial how to program device with ESPHome.
